const NEW_SNACK = "NEW_SNACK";
const SHOW_ACTIVE_SNACK = "SHOW_ACTIVE_SNACK";
const CLOSE_ACTIVE_SNACK = "CLOSE_ACTIVE_SNACK";

export default {
  NEW_SNACK,
  CLOSE_ACTIVE_SNACK,
  SHOW_ACTIVE_SNACK,
};
