const FETCH_DISH_SUCCEEDED = "FETCH_DISH_SUCCEEDED";
const FETCH_DISHES_SUCCEEDED = "FETCH_DISHES_SUCCEEDED";
const FETCH_DISH_FAILED = "FETCH_DISH_FAILED";
const FETCH_DISHES_FAILED = "FETCH_DISHES_FAILED";
const FETCH_DISH_REQUESTED = "FETCH_DISH_REQUESTED";
const FETCH_DISHES_REQUESTED = "FETCH_DISHES_REQUESTED";
const SELECTED_DISH_DETAILS = "SELECTED_DISH_DETAILS";

const dishesTypes = {
  FETCH_DISHES_REQUESTED,
  FETCH_DISH_REQUESTED,
  FETCH_DISHES_FAILED,
  FETCH_DISH_FAILED,
  FETCH_DISHES_SUCCEEDED,
  FETCH_DISH_SUCCEEDED,
  SELECTED_DISH_DETAILS,
};

export default dishesTypes;
